# Dependencies
markdown:         kramdown
kramdown:
  input: GFM

highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Enterprise Mac
tagline:          'Macs, Enterprise, good times.'
description:      'Macs, Enterprise, good times.'
url:              http://enterprisemac.bruienne.com
baseurl:          /
excerpt_separator: <!--more-->

author:
  name:           'Pepijn bruienne'
  url:            https://twitter.com/bruienne

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/bruienne/bruienne.github.io

theme:
  name:           Hyde
  author:         Mark Otto
  url:            https://twitter.com/mdo
  repo:           https://github.com/poole/hyde
